-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
require("config.neotree")
require("config.telescopeConf")
require("config.neovideConf")
require("config.neovimDefault")
require("config.intelephenseConf")
require("config.lsp")
require("config.vue")
-- require("config.liveserver")
