keymap("n", "<C-q>", ":q!<CR>", opts)
keymap("n", "<C-d>", ":bd!<CR>", opts)
keymap("n", "<C-s>", ":w!<CR>", opts)
keymap("n", "<c-t>", ":terminal<CR>", opts)
keymap("n", "<leader>E", ":Ranger<CR>", opts)
keymap("n", "<leader>e", ":Neotree toggle <CR>", opts)
keymap("n", "<leader>m", ":Telescope media_files<CR>", opts)
keymap("n", "<leader>fg", ":Telescope live_grep<CR>", opts)
-- keymap("n", "<C-f>", ":Neoformat<CR>", opts)
keymap("n", "<leader>c", ":VCoolor<CR>", opts)
keymap("n", "<leader>fc", ":Telescope colorscheme<CR>", opts)
keymap("n", "<leader>d", ":DBUIToggle<CR>", opts)
